---
name: Build and deploy krorvik/github-actions-runner

on:
  push:
    branches:
      - master

jobs:

  set_version:

    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setver.outputs.version }}

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Set version
        id: setver
        shell: bash
        run: |-
          MAJOR="1"
          MINOR="0"
          PATCH="$(git log --oneline | wc -l)"
          echo "::set-output name=version::$MAJOR.$MINOR.$PATCH"

  build_push:

    runs-on: ubuntu-latest
    needs: set_version

    steps:

      - name: checkout
        uses: actions/checkout@v1

      - name: Build
        shell: bash
        run: |-
          go build

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          path: ./
          username: ${{ secrets.DOCKER_LOGIN }}
          password:  ${{ secrets.DOCKER_PASSWORD }}
          repository: krorvik/github-actions-exporter
          tags: latest,${{ needs.set_version.outputs.version }}
